/**
 * Carbon.JS - A simple JavaScript framework
 *
 * Carbon.JS DOM Module - Basic DOM functions
 *
 * @author		Dmitry Polyuhov <admin@carbonjs.com>
 * @license		http://carbonjs.com/mit-license.txt
 * @version		1.1.0 (build 20100321)
 */
CarbonJS.modules.dom=true;CarbonJS.refreshCache=function(){CarbonJS.__cache={}};CarbonJS.extend({html:function(b){if(b==null){return this[0].innerHTML}else{var a=arguments[0];this.forEach(function(){this.innerHTML=a});CarbonJS.refreshCache();return this}},text:function(){return(this[0].textContent||this[0].innerText)},createDOM:function(){CarbonJS.checkModules("utilities");var g=[],k=0,d;while(d=arguments[k++]){if(typeof d=="string"){if(/^([a-zA-Z0-9]*)#([a-zA-Z0-9-_]+)(:[^:]+)*$/.test(d)||/^([a-zA-Z0-9*]+)?(\.([a-zA-Z0-9-_]+))?(:[^:]+)*$/.test(d)||/^(\w*)(\[(\w+)([=~\|\^\$\*]?)=?"?([^\]"]*)"?\])+(:[^:]+)*$/.test(d)){var b=Q(d),h=0,m;while(m=b[h++]){g.push(m)}}else{g.push(document.createTextNode(d))}}else{if(typeof d=="object"){if(!d.tag){g.push(d)}else{var c=document.createElement(d.tag);if(d.id){c.id=d.id}if(d.css){Q(c).css(d.css)}if(d.attr){Q(c).attr(d.attr)}if(d.children){var h=0,m,e=d.children;while(m=e[h++]){var b=Q().createDOM(m),f=0,l;while(l=b[f++]){c.appendChild(l)}}}g.push(c)}}}}return g},append:function(){var a=0,b;while(b=arguments[a++]){this.forEach(function(){var c=Q().createDOM(b),d=0,e;while(e=c[d++]){this.appendChild(e)}})}CarbonJS.refreshCache();return this},prepend:function(){var a=arguments.length-1,b;while(b=arguments[a--]){this.forEach(function(){var c=Q().createDOM(b),d=c.length-1,e;while(e=c[d--]){this.insertBefore(e,this.firstChild)}})}CarbonJS.refreshCache();return this},addBeforeIt:function(){var a=0,b;while(b=arguments[a++]){this.forEach(function(){var c=Q().createDOM(b),d=0,e;while(e=c[d++]){this.parentNode.insertBefore(e,this)}})}CarbonJS.refreshCache();return this},addAfterIt:function(){var a=arguments.length-1,b;while(b=arguments[a--]){this.forEach(function(){var c=Q().createDOM(b),d=c.length-1,e;while(e=c[d--]){this.parentNode.insertBefore(e,this.nextSibling)}})}CarbonJS.refreshCache();return this},clear:function(){if(arguments.length>0){var a=0,b;while(b=arguments[a++]){this.forEach(function(){QF(this,b).remove()})}}else{this.forEach(function(){var c=this;while(c.firstChild){c.removeChild(c.firstChild)}})}CarbonJS.refreshCache();return this},clone:function(a){return this[0].cloneNode(a||true)},remove:function(){this.forEach(function(){this.parentNode.removeChild(this)});CarbonJS.refreshCache();return this},parentNode:function(){return Q(this[0].parentNode)},firstChild:function(){if(CarbonJS.traversal){return Q(this[0].firstElementChild)}else{var a=this[0].firstChild;while(a&&a.nodeType!=1){a=a.nextSibling}return Q(a)}},lastChild:function(){if(CarbonJS.traversal){return Q(this[0].lastElementChild)}else{var a=this[0].lastChild;while(a&&a.nodeType!=1){a=a.previousSibling}return Q(a)}},nextSibling:function(){if(CarbonJS.traversal){return Q(this[0].nextElementSibling)}else{var a=this[0];while((a=a.nextSibling)&&a.nodeType!=1){}return Q(a)}},prevSibling:function(){if(CarbonJS.traversal){return Q(this[0].previousElementSibling)}else{var a=this[0];while((a=a.previousSibling)&&a.nodeType!=1){}return Q(a)}}});